### PR TITLE
Added Back-To-Top Button on the Page

### PR DESCRIPTION
**Pull request by Bhargav252000**
Working Back-To-Top button on the page.

### CODE REVIEW

**Comment by Bhargav252000** [comment]
For Issue #77

**Comment by ishandeveloper** [comment]
Hey @Bhargav252000 ! 
I just reviewed your changes, fantastic job! It looks sleek, thanks for taking the time to make this.

However, before, I merge this PR, can you decrease the size of the button on mobile devices? Currently, it looks so big and acts as an obstruction for the user.



Hit me up, once done and I'll merge this PR. Happy hacking ✨

**Comment by Bhargav252000** [comment]
@ishandeveloper Done !
Changed the size of the button in Mobile View..
I am glad that you liked the feature 💯

**Comment by ishandeveloper** [comment]
LGTM!

**Comment by ishandeveloper** [comment]
Hey @Bhargav252000 

Congrats on submitting your pull request.
You PR has been merged and the changes will be reflected on the website in a few minutes,.

Do leave a star, if you liked the repo ;)
### Happy hacking ! 🎊

**Pull request merged**
