### PR TITLE
Added pagination functionality

### PR DESCRIPTION
**Pull request by iarmankhan**
Added the pagination functionality, formatted some code in other files.

### CODE REVIEW

**Comment by iarmankhan** [comment]
I think the merge conflict is just because of code formatting, can you please take a look? @ishandeveloper

**Comment by ishandeveloper** [comment]
Hey @iarmankhan . Terrific job! The design scheme also looks so neat and consistent with the overall UI. Thanks for taking out the time to work on this one.

Congrats on submitting your pull request.
You PR has been merged and the changes will be reflected on the website in a few minutes,.

Do leave a star, if you liked the repo ;)
### Happy hacking ! 🎊

**Comment by iarmankhan** [comment]
Hey, Is everything alright with the live version? 
image

Page is being repeated and there are errors in console, also someone pagination code is their but it's not get overwritten by old code which I deleted. Please take a look.

**Comment by ishandeveloper** [comment]
Hey @iarmankhan !

Thank you so much for pointing that out, looks like it was due to some issues while resolving merge conflicts with #87 . I've reverted that PR for now, and will look into this, in a while.

Thanks for reporting again! Happy hacking! ✨

**Pull request merged**
