### PR TITLE
Added React JS Crash Course by Brad Traversy

### PR DESCRIPTION
**Pull request by parnexcodes**
Thanks for making this project Ishan!

### CODE REVIEW

**Comment by parnexcodes** [comment]
Issue #1

**Comment by parnexcodes** [comment]
Ugh sorry if it's messy , I was just trying to resolve conflicts but I guess I messed up.

**Comment by parnexcodes** [comment]
@ishandeveloper Hi, just fixed the conflicts . It's possible to merge now ? I'm still learning so hopefully I fixed it :)

**Comment by ishandeveloper** [comment]
Hey @parnexcodes !

Congrats on submitting your pull request.
You PR has been merged and the changes will be reflected on the website in a few minutes,.

Do leave a star, if you liked the repo ;)
### Happy hacking ! 🎊

**Pull request merged**
