### PR TITLE
ADDED : The Cherno C++ Playlist

### PR DESCRIPTION
**Pull request by TanishqSingla**
Added The Cherno C++ Playlist. The playlist focuses on the fundamentals of c++ and its behaviour

### CODE REVIEW

**Comment by TanishqSingla** [comment]
Resolved the conflicts, please check into that

**Comment by ishandeveloper** [comment]
Hey @TanishqSingla ! Thanks for resolving those conflicts, man. Almost everything looks good!

But, there is just one thing, currently, the web app doesn't support using images from other web sources, can you please either remove the img link or add one in the `courses\images` folder, and mention the file name?

Hit me up, once done and I'll merge this PR :)

**Comment by TanishqSingla** [comment]
Sorry I wasn't able to find any image with appropriate resolution, so I have to remove the url

**Comment by TanishqSingla** [comment]
So I added the image and everything is working fine on my side, you can check if it's working fine

**Comment by ishandeveloper** [comment]
LGTM @TanishqSingla !

Congrats on submitting your pull request and thank you for taking out the time to contribute in this project. Your PR has been merged and the changes will be reflected on the website in a few minutes,.

Do leave a star, if you liked the repo ;)
### Happy hacking ! 🎊

**Pull request merged**
