### PR TITLE
ADDED: Flutter & Dart - The Complete Flutter App Development Course

### PR DESCRIPTION
**Pull request by kchatr**
Added Flutter course for Issue #2

### CODE REVIEW

**Comment by ishandeveloper** [comment]
Hey @kchatr ,
Thanks for creating a Pull Request.

I'm sorry I can't merge this PR, because as per the contributing guidelines, only PR submissions which include free resources are valid. Please either commit the changes in this PR or close this one and create a new PR, with a free course.

**Comment by kchatr** [comment]
@ishandeveloper Apologies for that - I added another course I really like, and resolved the merge conflicts.
If there are any other issues with this PR let me know!

**Comment by ishandeveloper** [comment]
Thanks for the update @kchatr! 
and thank you resolving those merge conflicts, that saved me a lot of trouble ;)

Congrats on submitting your pull request.
You PR has been merged and the changes will be reflected on the website in a few minutes,.

Do leave a star, if you liked the repo ;)
### Happy hacking ! 🎊

**Comment by ishandeveloper** [comment]
> 
> 
> Thanks! Left a star as well :)
> Just wondering, do you know when these PRs will pass the review period? Do I have to wait the entire week, or how does it work?

Hey @kchatr . You'll have to wait for a period of one week, for your PR to mature in your hacktoberfest profile. This time window, allows the maintainers to review and mark PRs which are invalid and just merely created for a +1 to get that tshirt.

**Pull request merged**
